//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.19050
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BESEDa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=\"C:\\Users\\Danis\\Documents\\Visual Studio 2010\\Projects\\Klav_trenajor_B" +
            "ESEDa\\Klav_trenajor_BESEDa\\beseda.db\"")]
        public string besedaConnectionString {
            get {
                return ((string)(this["besedaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=\"C:\\Users\\Danis\\Desktop\\Зеленко\\Klav_trenajor_BESEDa - newD\\Klav_tren" +
            "ajor_BESEDa - newD\\Klav_trenajor_BESEDa\\bin\\Debug\\beseda\"")]
        public string besedaConnectionString1 {
            get {
                return ((string)(this["besedaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=\"C:\\Users\\Danis\\Desktop\\Зеленко\\Klav_trenajor_BESEDa - newD - копия\\K" +
            "lav_trenajor_BESEDa - newD\\Klav_trenajor_BESEDa\\bin\\Debug\\beseda\"")]
        public string besedaConnectionString2 {
            get {
                return ((string)(this["besedaConnectionString2"]));
            }
        }
    }
}
